params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: actor_critic
    separate: False
    space: 
      discrete:

    cnn:
      permute_input: True
      type: conv2d
      activation: relu
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237 
      convs:    
        - filters: 32
          kernel_size: 8
          strides: 4
          padding: 0
        - filters: 64
          kernel_size: 4
          strides: 2
          padding: 0
        - filters: 64
          kernel_size: 2
          strides: 1
          padding: 0
      
    mlp:
      units: [512]
      activation: relu
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237

  config:
    name: Crafter
    score_to_win: 900
    normalize_value: True
    normalize_input: False
    reward_shaper:
      #min_val: -1
      #max_val: 1
      scale_value: 1
    normalize_advantage: True
    gamma: 0.999
    tau: 0.95
    learning_rate: 8e-4
    lr_schedule: None
    kl_threshold: 0.01

    grad_norm: 1.0
    entropy_coef: 0.01
    truncate_grads: True
    e_clip: 0.2
    clip_value: False
    num_actors: 32
    horizon_length: 80
    minibatch_size: 1280
    mini_epochs: 2
    critic_coef: 1
    #schedule_entropy: True
    max_epochs: 1500

    env_name: CrafterNew-v1

    player:
      render: False
      games_num: 200
      n_game_life: 5
      deterministic: False
    
    use_sea: True
    sea_config:
      objective_dim: 64
      achievement_buffer_config:
        length: 8
        capacity: 512
        minimum_length: 4
        random_sampling: True
      mini_epochs: 1
      minibatch_size: 128
      truncate_grads: False
      normalize_input: False
      learning_rate: 2e-4
      truncate_grads: True
      grad_norm: 40.0

      network:
        name: actor_critic
        separate: False
        space: 
          discrete:

        cnn:
          permute_input: True
          type: conv2d
          activation: relu
          initializer:
            name: orthogonal_initializer
            gain: 1.41421356237 
          convs:    
            - filters: 32
              kernel_size: 8
              strides: 4
              padding: 0
            - filters: 64
              kernel_size: 4
              strides: 2
              padding: 0
            - filters: 64
              kernel_size: 2
              strides: 1
              padding: 0
          
        mlp:
          units: [256, 256]
          activation: relu
          initializer:
            name: orthogonal_initializer
            gain: 1.41421356237

